apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: obsidian-livesync

resources:
  - namespace.yaml
  - service-accounts.yaml
  - pvcs.yaml
  - deployment.yaml
  - httproute.yaml

generators:
  - secret-generator.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: obsidian-livesync
    includeSelectors: false

images:
  - name: couchdb
    newTag: "3.5"
